apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: container-agent
spec:
  project: default
  source:
    chart: container-agent
    repoURL: https://packagecloud.io/circleci/container-agent/helm
    targetRevision: 101.1.3
  destination:
    server: "https://kubernetes.default.svc"
    namespace: circleci
